// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_latency_array_array_softmax_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_latency_array_array_softmax_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_latency_array_array_softmax_config13_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> softmax_latency_array_array_softmax_config13_s::ap_ST_fsm_pp0_stage0 = "1";
const bool softmax_latency_array_array_softmax_config13_s::ap_const_boolean_1 = true;
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool softmax_latency_array_array_softmax_config13_s::ap_const_boolean_0 = false;
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_6 = "110";
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_F = "1111";
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_8 = "1000";
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_11 = "10001";
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_E = "1110";
const sc_lv<32> softmax_latency_array_array_softmax_config13_s::ap_const_lv32_1D = "11101";

softmax_latency_array_array_softmax_config13_s::softmax_latency_array_array_softmax_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    exp_table7_U = new softmax_latency_array_array_softmax_config13_s_exp_table7("exp_table7_U");
    exp_table7_U->clk(ap_clk);
    exp_table7_U->reset(ap_rst);
    exp_table7_U->address0(exp_table7_address0);
    exp_table7_U->ce0(exp_table7_ce0);
    exp_table7_U->q0(exp_table7_q0);
    exp_table7_U->address1(exp_table7_address1);
    exp_table7_U->ce1(exp_table7_ce1);
    exp_table7_U->q1(exp_table7_q1);
    exp_table7_U->address2(exp_table7_address2);
    exp_table7_U->ce2(exp_table7_ce2);
    exp_table7_U->q2(exp_table7_q2);
    exp_table7_U->address3(exp_table7_address3);
    exp_table7_U->ce3(exp_table7_ce3);
    exp_table7_U->q3(exp_table7_q3);
    exp_table7_U->address4(exp_table7_address4);
    exp_table7_U->ce4(exp_table7_ce4);
    exp_table7_U->q4(exp_table7_q4);
    invert_table8_U = new softmax_latency_array_array_softmax_config13_s_invert_tabcud("invert_table8_U");
    invert_table8_U->clk(ap_clk);
    invert_table8_U->reset(ap_rst);
    invert_table8_U->address0(invert_table8_address0);
    invert_table8_U->ce0(invert_table8_ce0);
    invert_table8_U->q0(invert_table8_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_1_fu_517_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exp_table7_q2 );

    SC_METHOD(thread_add_ln703_1_fu_517_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exp_table7_q4 );

    SC_METHOD(thread_add_ln703_1_fu_517_p2);
    sensitive << ( add_ln703_1_fu_517_p0 );
    sensitive << ( add_ln703_1_fu_517_p1 );

    SC_METHOD(thread_add_ln703_2_fu_523_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exp_table7_q3 );

    SC_METHOD(thread_add_ln703_2_fu_523_p2);
    sensitive << ( add_ln703_1_fu_517_p2 );
    sensitive << ( add_ln703_2_fu_523_p1 );

    SC_METHOD(thread_add_ln703_fu_529_p2);
    sensitive << ( exp_res_0_V_reg_656 );
    sensitive << ( exp_res_1_V_reg_662 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op7 );
    sensitive << ( io_acc_block_signal_op93 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op7 );
    sensitive << ( io_acc_block_signal_op93 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( io_acc_block_signal_op7 );
    sensitive << ( io_acc_block_signal_op93 );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( io_acc_block_signal_op7 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);
    sensitive << ( io_acc_block_signal_op93 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_idle_pp0_0to4);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to4 );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_0_V_empty_n );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_1_V_empty_n );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_2_V_empty_n );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_3_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_3_V_empty_n );

    SC_METHOD(thread_data_V_data_3_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_4_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_V_data_4_V_empty_n );

    SC_METHOD(thread_data_V_data_4_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_sum_V_fu_533_p2);
    sensitive << ( add_ln703_2_reg_683 );
    sensitive << ( add_ln703_fu_529_p2 );

    SC_METHOD(thread_exp_table7_address0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln157_fu_452_p1 );

    SC_METHOD(thread_exp_table7_address1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln157_1_fu_467_p1 );

    SC_METHOD(thread_exp_table7_address2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln157_2_fu_482_p1 );

    SC_METHOD(thread_exp_table7_address3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln157_3_fu_497_p1 );

    SC_METHOD(thread_exp_table7_address4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln157_4_fu_512_p1 );

    SC_METHOD(thread_exp_table7_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table7_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table7_ce2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table7_ce3);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_exp_table7_ce4);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_invert_table8_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( zext_ln166_fu_548_p1 );

    SC_METHOD(thread_invert_table8_ce0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_io_acc_block_signal_op7);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( data_V_data_4_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op93);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( res_V_data_4_V_full_n );

    SC_METHOD(thread_mul_ln1118_1_fu_315_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exp_res_1_V_reg_662_pp0_iter3_reg );

    SC_METHOD(thread_mul_ln1118_1_fu_315_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( sext_ln167_fu_553_p1 );

    SC_METHOD(thread_mul_ln1118_1_fu_315_p2);
    sensitive << ( mul_ln1118_1_fu_315_p0 );
    sensitive << ( mul_ln1118_1_fu_315_p1 );

    SC_METHOD(thread_mul_ln1118_2_fu_314_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exp_res_2_V_reg_668_pp0_iter3_reg );

    SC_METHOD(thread_mul_ln1118_2_fu_314_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( sext_ln167_fu_553_p1 );

    SC_METHOD(thread_mul_ln1118_2_fu_314_p2);
    sensitive << ( mul_ln1118_2_fu_314_p0 );
    sensitive << ( mul_ln1118_2_fu_314_p1 );

    SC_METHOD(thread_mul_ln1118_3_fu_313_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exp_res_3_V_reg_673_pp0_iter3_reg );

    SC_METHOD(thread_mul_ln1118_3_fu_313_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( sext_ln167_fu_553_p1 );

    SC_METHOD(thread_mul_ln1118_3_fu_313_p2);
    sensitive << ( mul_ln1118_3_fu_313_p0 );
    sensitive << ( mul_ln1118_3_fu_313_p1 );

    SC_METHOD(thread_mul_ln1118_4_fu_311_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exp_res_4_V_reg_678_pp0_iter3_reg );

    SC_METHOD(thread_mul_ln1118_4_fu_311_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( sext_ln167_fu_553_p1 );

    SC_METHOD(thread_mul_ln1118_4_fu_311_p2);
    sensitive << ( mul_ln1118_4_fu_311_p0 );
    sensitive << ( mul_ln1118_4_fu_311_p1 );

    SC_METHOD(thread_mul_ln1118_fu_312_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exp_res_0_V_reg_656_pp0_iter3_reg );

    SC_METHOD(thread_mul_ln1118_fu_312_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( sext_ln167_fu_553_p1 );

    SC_METHOD(thread_mul_ln1118_fu_312_p2);
    sensitive << ( mul_ln1118_fu_312_p0 );
    sensitive << ( mul_ln1118_fu_312_p1 );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_0_V_full_n );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_0_V_reg_698 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_1_V_full_n );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_1_V_reg_703 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_2_V_full_n );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_2_V_reg_708 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_3_V_blk_n);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_3_V_full_n );

    SC_METHOD(thread_res_V_data_3_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_3_V_reg_713 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_3_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_4_V_blk_n);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( res_V_data_4_V_full_n );

    SC_METHOD(thread_res_V_data_4_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_data_4_V_reg_718 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_V_data_4_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_sext_ln167_fu_553_p1);
    sensitive << ( inv_exp_sum_V_reg_693 );

    SC_METHOD(thread_y_V_1_fu_457_p4);
    sensitive << ( data_V_data_1_V_dout );

    SC_METHOD(thread_y_V_2_fu_472_p4);
    sensitive << ( data_V_data_2_V_dout );

    SC_METHOD(thread_y_V_3_fu_487_p4);
    sensitive << ( data_V_data_3_V_dout );

    SC_METHOD(thread_y_V_4_fu_502_p4);
    sensitive << ( data_V_data_4_V_dout );

    SC_METHOD(thread_y_V_5_fu_538_p4);
    sensitive << ( exp_sum_V_fu_533_p2 );

    SC_METHOD(thread_y_V_fu_442_p4);
    sensitive << ( data_V_data_0_V_dout );

    SC_METHOD(thread_zext_ln157_1_fu_467_p1);
    sensitive << ( y_V_1_fu_457_p4 );

    SC_METHOD(thread_zext_ln157_2_fu_482_p1);
    sensitive << ( y_V_2_fu_472_p4 );

    SC_METHOD(thread_zext_ln157_3_fu_497_p1);
    sensitive << ( y_V_3_fu_487_p4 );

    SC_METHOD(thread_zext_ln157_4_fu_512_p1);
    sensitive << ( y_V_4_fu_502_p4 );

    SC_METHOD(thread_zext_ln157_fu_452_p1);
    sensitive << ( y_V_fu_442_p4 );

    SC_METHOD(thread_zext_ln166_fu_548_p1);
    sensitive << ( y_V_5_fu_538_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_latency_array_array_softmax_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, data_V_data_3_V_dout, "(port)data_V_data_3_V_dout");
    sc_trace(mVcdFile, data_V_data_3_V_empty_n, "(port)data_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_V_data_3_V_read, "(port)data_V_data_3_V_read");
    sc_trace(mVcdFile, data_V_data_4_V_dout, "(port)data_V_data_4_V_dout");
    sc_trace(mVcdFile, data_V_data_4_V_empty_n, "(port)data_V_data_4_V_empty_n");
    sc_trace(mVcdFile, data_V_data_4_V_read, "(port)data_V_data_4_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
    sc_trace(mVcdFile, res_V_data_3_V_din, "(port)res_V_data_3_V_din");
    sc_trace(mVcdFile, res_V_data_3_V_full_n, "(port)res_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_V_data_3_V_write, "(port)res_V_data_3_V_write");
    sc_trace(mVcdFile, res_V_data_4_V_din, "(port)res_V_data_4_V_din");
    sc_trace(mVcdFile, res_V_data_4_V_full_n, "(port)res_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_V_data_4_V_write, "(port)res_V_data_4_V_write");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "(port)data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "(port)data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "(port)data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_V_data_3_V_blk_n, "(port)data_V_data_3_V_blk_n");
    sc_trace(mVcdFile, data_V_data_4_V_blk_n, "(port)data_V_data_4_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "(port)res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "(port)res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "(port)res_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_3_V_blk_n, "(port)res_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_V_data_4_V_blk_n, "(port)res_V_data_4_V_blk_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, io_acc_block_signal_op7, "io_acc_block_signal_op7");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, io_acc_block_signal_op93, "io_acc_block_signal_op93");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exp_table7_address0, "exp_table7_address0");
    sc_trace(mVcdFile, exp_table7_ce0, "exp_table7_ce0");
    sc_trace(mVcdFile, exp_table7_q0, "exp_table7_q0");
    sc_trace(mVcdFile, exp_table7_address1, "exp_table7_address1");
    sc_trace(mVcdFile, exp_table7_ce1, "exp_table7_ce1");
    sc_trace(mVcdFile, exp_table7_q1, "exp_table7_q1");
    sc_trace(mVcdFile, exp_table7_address2, "exp_table7_address2");
    sc_trace(mVcdFile, exp_table7_ce2, "exp_table7_ce2");
    sc_trace(mVcdFile, exp_table7_q2, "exp_table7_q2");
    sc_trace(mVcdFile, exp_table7_address3, "exp_table7_address3");
    sc_trace(mVcdFile, exp_table7_ce3, "exp_table7_ce3");
    sc_trace(mVcdFile, exp_table7_q3, "exp_table7_q3");
    sc_trace(mVcdFile, exp_table7_address4, "exp_table7_address4");
    sc_trace(mVcdFile, exp_table7_ce4, "exp_table7_ce4");
    sc_trace(mVcdFile, exp_table7_q4, "exp_table7_q4");
    sc_trace(mVcdFile, invert_table8_address0, "invert_table8_address0");
    sc_trace(mVcdFile, invert_table8_ce0, "invert_table8_ce0");
    sc_trace(mVcdFile, invert_table8_q0, "invert_table8_q0");
    sc_trace(mVcdFile, exp_res_0_V_reg_656, "exp_res_0_V_reg_656");
    sc_trace(mVcdFile, exp_res_0_V_reg_656_pp0_iter2_reg, "exp_res_0_V_reg_656_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_0_V_reg_656_pp0_iter3_reg, "exp_res_0_V_reg_656_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_662, "exp_res_1_V_reg_662");
    sc_trace(mVcdFile, exp_res_1_V_reg_662_pp0_iter2_reg, "exp_res_1_V_reg_662_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_1_V_reg_662_pp0_iter3_reg, "exp_res_1_V_reg_662_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_668, "exp_res_2_V_reg_668");
    sc_trace(mVcdFile, exp_res_2_V_reg_668_pp0_iter2_reg, "exp_res_2_V_reg_668_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_2_V_reg_668_pp0_iter3_reg, "exp_res_2_V_reg_668_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_673, "exp_res_3_V_reg_673");
    sc_trace(mVcdFile, exp_res_3_V_reg_673_pp0_iter2_reg, "exp_res_3_V_reg_673_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_3_V_reg_673_pp0_iter3_reg, "exp_res_3_V_reg_673_pp0_iter3_reg");
    sc_trace(mVcdFile, exp_res_4_V_reg_678, "exp_res_4_V_reg_678");
    sc_trace(mVcdFile, exp_res_4_V_reg_678_pp0_iter2_reg, "exp_res_4_V_reg_678_pp0_iter2_reg");
    sc_trace(mVcdFile, exp_res_4_V_reg_678_pp0_iter3_reg, "exp_res_4_V_reg_678_pp0_iter3_reg");
    sc_trace(mVcdFile, add_ln703_2_fu_523_p2, "add_ln703_2_fu_523_p2");
    sc_trace(mVcdFile, add_ln703_2_reg_683, "add_ln703_2_reg_683");
    sc_trace(mVcdFile, inv_exp_sum_V_reg_693, "inv_exp_sum_V_reg_693");
    sc_trace(mVcdFile, tmp_data_0_V_reg_698, "tmp_data_0_V_reg_698");
    sc_trace(mVcdFile, tmp_data_1_V_reg_703, "tmp_data_1_V_reg_703");
    sc_trace(mVcdFile, tmp_data_2_V_reg_708, "tmp_data_2_V_reg_708");
    sc_trace(mVcdFile, tmp_data_3_V_reg_713, "tmp_data_3_V_reg_713");
    sc_trace(mVcdFile, tmp_data_4_V_reg_718, "tmp_data_4_V_reg_718");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln157_fu_452_p1, "zext_ln157_fu_452_p1");
    sc_trace(mVcdFile, zext_ln157_1_fu_467_p1, "zext_ln157_1_fu_467_p1");
    sc_trace(mVcdFile, zext_ln157_2_fu_482_p1, "zext_ln157_2_fu_482_p1");
    sc_trace(mVcdFile, zext_ln157_3_fu_497_p1, "zext_ln157_3_fu_497_p1");
    sc_trace(mVcdFile, zext_ln157_4_fu_512_p1, "zext_ln157_4_fu_512_p1");
    sc_trace(mVcdFile, zext_ln166_fu_548_p1, "zext_ln166_fu_548_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, mul_ln1118_4_fu_311_p0, "mul_ln1118_4_fu_311_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_311_p1, "mul_ln1118_4_fu_311_p1");
    sc_trace(mVcdFile, sext_ln167_fu_553_p1, "sext_ln167_fu_553_p1");
    sc_trace(mVcdFile, mul_ln1118_fu_312_p0, "mul_ln1118_fu_312_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_312_p1, "mul_ln1118_fu_312_p1");
    sc_trace(mVcdFile, mul_ln1118_3_fu_313_p0, "mul_ln1118_3_fu_313_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_313_p1, "mul_ln1118_3_fu_313_p1");
    sc_trace(mVcdFile, mul_ln1118_2_fu_314_p0, "mul_ln1118_2_fu_314_p0");
    sc_trace(mVcdFile, mul_ln1118_2_fu_314_p1, "mul_ln1118_2_fu_314_p1");
    sc_trace(mVcdFile, mul_ln1118_1_fu_315_p0, "mul_ln1118_1_fu_315_p0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_315_p1, "mul_ln1118_1_fu_315_p1");
    sc_trace(mVcdFile, y_V_fu_442_p4, "y_V_fu_442_p4");
    sc_trace(mVcdFile, y_V_1_fu_457_p4, "y_V_1_fu_457_p4");
    sc_trace(mVcdFile, y_V_2_fu_472_p4, "y_V_2_fu_472_p4");
    sc_trace(mVcdFile, y_V_3_fu_487_p4, "y_V_3_fu_487_p4");
    sc_trace(mVcdFile, y_V_4_fu_502_p4, "y_V_4_fu_502_p4");
    sc_trace(mVcdFile, add_ln703_1_fu_517_p0, "add_ln703_1_fu_517_p0");
    sc_trace(mVcdFile, add_ln703_1_fu_517_p1, "add_ln703_1_fu_517_p1");
    sc_trace(mVcdFile, add_ln703_1_fu_517_p2, "add_ln703_1_fu_517_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_523_p1, "add_ln703_2_fu_523_p1");
    sc_trace(mVcdFile, add_ln703_fu_529_p2, "add_ln703_fu_529_p2");
    sc_trace(mVcdFile, exp_sum_V_fu_533_p2, "exp_sum_V_fu_533_p2");
    sc_trace(mVcdFile, y_V_5_fu_538_p4, "y_V_5_fu_538_p4");
    sc_trace(mVcdFile, mul_ln1118_fu_312_p2, "mul_ln1118_fu_312_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_315_p2, "mul_ln1118_1_fu_315_p2");
    sc_trace(mVcdFile, mul_ln1118_2_fu_314_p2, "mul_ln1118_2_fu_314_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_313_p2, "mul_ln1118_3_fu_313_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_311_p2, "mul_ln1118_4_fu_311_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to4, "ap_idle_pp0_0to4");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

softmax_latency_array_array_softmax_config13_s::~softmax_latency_array_array_softmax_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete exp_table7_U;
    delete invert_table8_U;
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln703_2_reg_683 = add_ln703_2_fu_523_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        exp_res_0_V_reg_656 = exp_table7_q0.read();
        exp_res_1_V_reg_662 = exp_table7_q1.read();
        exp_res_2_V_reg_668 = exp_table7_q2.read();
        exp_res_3_V_reg_673 = exp_table7_q3.read();
        exp_res_4_V_reg_678 = exp_table7_q4.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exp_res_0_V_reg_656_pp0_iter2_reg = exp_res_0_V_reg_656.read();
        exp_res_0_V_reg_656_pp0_iter3_reg = exp_res_0_V_reg_656_pp0_iter2_reg.read();
        exp_res_1_V_reg_662_pp0_iter2_reg = exp_res_1_V_reg_662.read();
        exp_res_1_V_reg_662_pp0_iter3_reg = exp_res_1_V_reg_662_pp0_iter2_reg.read();
        exp_res_2_V_reg_668_pp0_iter2_reg = exp_res_2_V_reg_668.read();
        exp_res_2_V_reg_668_pp0_iter3_reg = exp_res_2_V_reg_668_pp0_iter2_reg.read();
        exp_res_3_V_reg_673_pp0_iter2_reg = exp_res_3_V_reg_673.read();
        exp_res_3_V_reg_673_pp0_iter3_reg = exp_res_3_V_reg_673_pp0_iter2_reg.read();
        exp_res_4_V_reg_678_pp0_iter2_reg = exp_res_4_V_reg_678.read();
        exp_res_4_V_reg_678_pp0_iter3_reg = exp_res_4_V_reg_678_pp0_iter2_reg.read();
        inv_exp_sum_V_reg_693 = invert_table8_q0.read();
        tmp_data_0_V_reg_698 = mul_ln1118_fu_312_p2.read().range(29, 14);
        tmp_data_1_V_reg_703 = mul_ln1118_1_fu_315_p2.read().range(29, 14);
        tmp_data_2_V_reg_708 = mul_ln1118_2_fu_314_p2.read().range(29, 14);
        tmp_data_3_V_reg_713 = mul_ln1118_3_fu_313_p2.read().range(29, 14);
        tmp_data_4_V_reg_718 = mul_ln1118_4_fu_311_p2.read().range(29, 14);
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_1_fu_517_p0() {
    add_ln703_1_fu_517_p0 = exp_table7_q2.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_1_fu_517_p1() {
    add_ln703_1_fu_517_p1 = exp_table7_q4.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_1_fu_517_p2() {
    add_ln703_1_fu_517_p2 = (!add_ln703_1_fu_517_p0.read().is_01() || !add_ln703_1_fu_517_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(add_ln703_1_fu_517_p0.read()) + sc_bigint<18>(add_ln703_1_fu_517_p1.read()));
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_2_fu_523_p1() {
    add_ln703_2_fu_523_p1 = exp_table7_q3.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_2_fu_523_p2() {
    add_ln703_2_fu_523_p2 = (!add_ln703_1_fu_517_p2.read().is_01() || !add_ln703_2_fu_523_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln703_1_fu_517_p2.read()) + sc_bigint<18>(add_ln703_2_fu_523_p1.read()));
}

void softmax_latency_array_array_softmax_config13_s::thread_add_ln703_fu_529_p2() {
    add_ln703_fu_529_p2 = (!exp_res_0_V_reg_656.read().is_01() || !exp_res_1_V_reg_662.read().is_01())? sc_lv<18>(): (sc_bigint<18>(exp_res_0_V_reg_656.read()) + sc_bigint<18>(exp_res_1_V_reg_662.read()));
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op7.read()))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op93.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read())));
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op7.read()))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op93.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read())));
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
  (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
   esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op7.read()))) || (esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op93.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read())));
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op7.read()));
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op93.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_idle_pp0_0to4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0_0to4 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to4 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to4.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n.read();
    } else {
        data_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_V_data_3_V_read = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n.read();
    } else {
        data_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_data_V_data_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_4_V_read = ap_const_logic_1;
    } else {
        data_V_data_4_V_read = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_sum_V_fu_533_p2() {
    exp_sum_V_fu_533_p2 = (!add_ln703_2_reg_683.read().is_01() || !add_ln703_fu_529_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(add_ln703_2_reg_683.read()) + sc_biguint<18>(add_ln703_fu_529_p2.read()));
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_address0() {
    exp_table7_address0 =  (sc_lv<10>) (zext_ln157_fu_452_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_address1() {
    exp_table7_address1 =  (sc_lv<10>) (zext_ln157_1_fu_467_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_address2() {
    exp_table7_address2 =  (sc_lv<10>) (zext_ln157_2_fu_482_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_address3() {
    exp_table7_address3 =  (sc_lv<10>) (zext_ln157_3_fu_497_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_address4() {
    exp_table7_address4 =  (sc_lv<10>) (zext_ln157_4_fu_512_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table7_ce0 = ap_const_logic_1;
    } else {
        exp_table7_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table7_ce1 = ap_const_logic_1;
    } else {
        exp_table7_ce1 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_ce2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table7_ce2 = ap_const_logic_1;
    } else {
        exp_table7_ce2 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_ce3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table7_ce3 = ap_const_logic_1;
    } else {
        exp_table7_ce3 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_exp_table7_ce4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_table7_ce4 = ap_const_logic_1;
    } else {
        exp_table7_ce4 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_invert_table8_address0() {
    invert_table8_address0 =  (sc_lv<10>) (zext_ln166_fu_548_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_invert_table8_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        invert_table8_ce0 = ap_const_logic_1;
    } else {
        invert_table8_ce0 = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_io_acc_block_signal_op7() {
    io_acc_block_signal_op7 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read() & data_V_data_3_V_empty_n.read() & data_V_data_4_V_empty_n.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_io_acc_block_signal_op93() {
    io_acc_block_signal_op93 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read() & res_V_data_3_V_full_n.read() & res_V_data_4_V_full_n.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_1_fu_315_p0() {
    mul_ln1118_1_fu_315_p0 = exp_res_1_V_reg_662_pp0_iter3_reg.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_1_fu_315_p1() {
    mul_ln1118_1_fu_315_p1 =  (sc_lv<18>) (sext_ln167_fu_553_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_1_fu_315_p2() {
    mul_ln1118_1_fu_315_p2 = (!mul_ln1118_1_fu_315_p0.read().is_01() || !mul_ln1118_1_fu_315_p1.read().is_01())? sc_lv<30>(): sc_bigint<18>(mul_ln1118_1_fu_315_p0.read()) * sc_bigint<18>(mul_ln1118_1_fu_315_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_2_fu_314_p0() {
    mul_ln1118_2_fu_314_p0 = exp_res_2_V_reg_668_pp0_iter3_reg.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_2_fu_314_p1() {
    mul_ln1118_2_fu_314_p1 =  (sc_lv<18>) (sext_ln167_fu_553_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_2_fu_314_p2() {
    mul_ln1118_2_fu_314_p2 = (!mul_ln1118_2_fu_314_p0.read().is_01() || !mul_ln1118_2_fu_314_p1.read().is_01())? sc_lv<30>(): sc_bigint<18>(mul_ln1118_2_fu_314_p0.read()) * sc_bigint<18>(mul_ln1118_2_fu_314_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_3_fu_313_p0() {
    mul_ln1118_3_fu_313_p0 = exp_res_3_V_reg_673_pp0_iter3_reg.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_3_fu_313_p1() {
    mul_ln1118_3_fu_313_p1 =  (sc_lv<18>) (sext_ln167_fu_553_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_3_fu_313_p2() {
    mul_ln1118_3_fu_313_p2 = (!mul_ln1118_3_fu_313_p0.read().is_01() || !mul_ln1118_3_fu_313_p1.read().is_01())? sc_lv<30>(): sc_bigint<18>(mul_ln1118_3_fu_313_p0.read()) * sc_bigint<18>(mul_ln1118_3_fu_313_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_4_fu_311_p0() {
    mul_ln1118_4_fu_311_p0 = exp_res_4_V_reg_678_pp0_iter3_reg.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_4_fu_311_p1() {
    mul_ln1118_4_fu_311_p1 =  (sc_lv<18>) (sext_ln167_fu_553_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_4_fu_311_p2() {
    mul_ln1118_4_fu_311_p2 = (!mul_ln1118_4_fu_311_p0.read().is_01() || !mul_ln1118_4_fu_311_p1.read().is_01())? sc_lv<30>(): sc_bigint<18>(mul_ln1118_4_fu_311_p0.read()) * sc_bigint<18>(mul_ln1118_4_fu_311_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_fu_312_p0() {
    mul_ln1118_fu_312_p0 = exp_res_0_V_reg_656_pp0_iter3_reg.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_fu_312_p1() {
    mul_ln1118_fu_312_p1 =  (sc_lv<18>) (sext_ln167_fu_553_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_mul_ln1118_fu_312_p2() {
    mul_ln1118_fu_312_p2 = (!mul_ln1118_fu_312_p0.read().is_01() || !mul_ln1118_fu_312_p1.read().is_01())? sc_lv<30>(): sc_bigint<18>(mul_ln1118_fu_312_p0.read()) * sc_bigint<18>(mul_ln1118_fu_312_p1.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = tmp_data_0_V_reg_698.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = tmp_data_1_V_reg_703.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = tmp_data_2_V_reg_708.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n.read();
    } else {
        res_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_3_V_din() {
    res_V_data_3_V_din = tmp_data_3_V_reg_713.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_V_data_3_V_write = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n.read();
    } else {
        res_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_4_V_din() {
    res_V_data_4_V_din = tmp_data_4_V_reg_718.read();
}

void softmax_latency_array_array_softmax_config13_s::thread_res_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_V_data_4_V_write = ap_const_logic_0;
    }
}

void softmax_latency_array_array_softmax_config13_s::thread_sext_ln167_fu_553_p1() {
    sext_ln167_fu_553_p1 = esl_sext<30,18>(inv_exp_sum_V_reg_693.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_1_fu_457_p4() {
    y_V_1_fu_457_p4 = data_V_data_1_V_dout.read().range(15, 6);
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_2_fu_472_p4() {
    y_V_2_fu_472_p4 = data_V_data_2_V_dout.read().range(15, 6);
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_3_fu_487_p4() {
    y_V_3_fu_487_p4 = data_V_data_3_V_dout.read().range(15, 6);
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_4_fu_502_p4() {
    y_V_4_fu_502_p4 = data_V_data_4_V_dout.read().range(15, 6);
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_5_fu_538_p4() {
    y_V_5_fu_538_p4 = exp_sum_V_fu_533_p2.read().range(17, 8);
}

void softmax_latency_array_array_softmax_config13_s::thread_y_V_fu_442_p4() {
    y_V_fu_442_p4 = data_V_data_0_V_dout.read().range(15, 6);
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln157_1_fu_467_p1() {
    zext_ln157_1_fu_467_p1 = esl_zext<64,10>(y_V_1_fu_457_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln157_2_fu_482_p1() {
    zext_ln157_2_fu_482_p1 = esl_zext<64,10>(y_V_2_fu_472_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln157_3_fu_497_p1() {
    zext_ln157_3_fu_497_p1 = esl_zext<64,10>(y_V_3_fu_487_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln157_4_fu_512_p1() {
    zext_ln157_4_fu_512_p1 = esl_zext<64,10>(y_V_4_fu_502_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln157_fu_452_p1() {
    zext_ln157_fu_452_p1 = esl_zext<64,10>(y_V_fu_442_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_zext_ln166_fu_548_p1() {
    zext_ln166_fu_548_p1 = esl_zext<64,10>(y_V_5_fu_538_p4.read());
}

void softmax_latency_array_array_softmax_config13_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

