# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nicolo/cernbox/pynq_nn_axis/dma_test_pynq_float/dma_test_pynq_v2/dma_test_pynq.srcs/sources_1/bd/design_1/ip/design_1_myproject_axi_0_7/design_1_myproject_axi_0_7.xci
# IP: The module: 'design_1_myproject_axi_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nicolo/cernbox/pynq_nn_axis/dma_test_pynq_float/dma_test_pynq_v2/dma_test_pynq.srcs/sources_1/bd/design_1/ip/design_1_myproject_axi_0_7/constraints/myproject_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myproject_axi_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/nicolo/cernbox/pynq_nn_axis/dma_test_pynq_float/dma_test_pynq_v2/dma_test_pynq.srcs/sources_1/bd/design_1/ip/design_1_myproject_axi_0_7/design_1_myproject_axi_0_7.xci
# IP: The module: 'design_1_myproject_axi_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nicolo/cernbox/pynq_nn_axis/dma_test_pynq_float/dma_test_pynq_v2/dma_test_pynq.srcs/sources_1/bd/design_1/ip/design_1_myproject_axi_0_7/constraints/myproject_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_myproject_axi_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
