// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _myproject_axi_HH_
#define _myproject_axi_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject.h"
#include "myproject_axi_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct myproject_axi : public sc_module {
    // Port declarations 28
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<16> > in_r_TDATA;
    sc_in< sc_logic > in_r_TVALID;
    sc_out< sc_logic > in_r_TREADY;
    sc_in< sc_logic > in_r_TLAST;
    sc_out< sc_lv<16> > out_r_TDATA;
    sc_out< sc_logic > out_r_TVALID;
    sc_in< sc_logic > out_r_TREADY;
    sc_out< sc_logic > out_r_TLAST;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    myproject_axi(sc_module_name name);
    SC_HAS_PROCESS(myproject_axi);

    ~myproject_axi();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    myproject_axi_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* myproject_axi_AXILiteS_s_axi_U;
    myproject* grp_myproject_fu_102;
    regslice_both<16>* regslice_both_in_data_V_U;
    regslice_both_w1<1>* regslice_both_w1_in_last_U;
    regslice_both<16>* regslice_both_out_data_V_U;
    regslice_both_w1<1>* regslice_both_w1_out_last_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > in_r_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > out_r_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<16> > in_data_V_val_reg_214;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<16> > in_data_V_val1_reg_219;
    sc_signal< sc_lv<16> > in_data_V_val3_reg_224;
    sc_signal< sc_lv<16> > in_data_V_val5_reg_229;
    sc_signal< sc_lv<16> > in_data_V_val7_reg_234;
    sc_signal< sc_lv<16> > in_data_V_val9_reg_239;
    sc_signal< sc_lv<16> > in_data_V_val2_reg_244;
    sc_signal< sc_lv<16> > in_data_V_val4_reg_249;
    sc_signal< sc_lv<16> > in_data_V_val6_reg_254;
    sc_signal< sc_lv<16> > in_data_V_val8_reg_259;
    sc_signal< sc_lv<16> > in_data_V_val10_reg_264;
    sc_signal< sc_lv<16> > in_data_V_val11_reg_269;
    sc_signal< sc_lv<16> > in_data_V_val12_reg_274;
    sc_signal< sc_lv<16> > in_data_V_val13_reg_279;
    sc_signal< sc_lv<16> > in_data_V_val14_reg_284;
    sc_signal< sc_lv<16> > grp_myproject_fu_102_layer13_out_0_V;
    sc_signal< sc_lv<16> > grp_myproject_fu_102_layer13_out_1_V;
    sc_signal< sc_lv<16> > grp_myproject_fu_102_layer13_out_2_V;
    sc_signal< sc_lv<16> > grp_myproject_fu_102_layer13_out_3_V;
    sc_signal< sc_lv<16> > grp_myproject_fu_102_layer13_out_4_V;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_start;
    sc_signal< sc_logic > grp_myproject_fu_102_layer13_out_0_V_ap_vld;
    sc_signal< sc_logic > grp_myproject_fu_102_layer13_out_1_V_ap_vld;
    sc_signal< sc_logic > grp_myproject_fu_102_layer13_out_2_V_ap_vld;
    sc_signal< sc_logic > grp_myproject_fu_102_layer13_out_3_V_ap_vld;
    sc_signal< sc_logic > grp_myproject_fu_102_layer13_out_4_V_ap_vld;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_done;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_ready;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_idle;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_continue;
    sc_signal< sc_logic > grp_myproject_fu_102_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > ap_sync_grp_myproject_fu_102_ap_ready;
    sc_signal< sc_logic > ap_sync_grp_myproject_fu_102_ap_done;
    sc_signal< bool > ap_block_state18_on_subcall_done;
    sc_signal< sc_logic > ap_sync_reg_grp_myproject_fu_102_ap_ready;
    sc_signal< sc_logic > ap_sync_reg_grp_myproject_fu_102_ap_done;
    sc_signal< sc_lv<256> > in_local_V_fu_58;
    sc_signal< sc_lv<16> > out_local_0_fu_62;
    sc_signal< sc_lv<16> > out_local_1_fu_66;
    sc_signal< sc_lv<16> > out_local_2_fu_70;
    sc_signal< sc_lv<16> > out_local_3_fu_74;
    sc_signal< sc_lv<16> > out_local_4_fu_78;
    sc_signal< sc_lv<256> > in_local_V_1_fu_132_p17;
    sc_signal< sc_logic > regslice_both_out_data_V_U_apdone_blk;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    sc_signal< sc_logic > regslice_both_in_data_V_U_apdone_blk;
    sc_signal< sc_lv<16> > in_r_TDATA_int;
    sc_signal< sc_logic > in_r_TVALID_int;
    sc_signal< sc_logic > in_r_TREADY_int;
    sc_signal< sc_logic > regslice_both_in_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_w1_in_last_U_apdone_blk;
    sc_signal< sc_logic > in_r_TLAST_int;
    sc_signal< sc_logic > regslice_both_w1_in_last_U_vld_out;
    sc_signal< sc_logic > regslice_both_w1_in_last_U_ack_in;
    sc_signal< sc_lv<16> > out_r_TDATA_int;
    sc_signal< sc_logic > out_r_TVALID_int;
    sc_signal< sc_logic > out_r_TREADY_int;
    sc_signal< sc_logic > regslice_both_out_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_w1_out_last_U_apdone_blk;
    sc_signal< sc_logic > out_r_TLAST_int;
    sc_signal< sc_logic > regslice_both_w1_out_last_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_w1_out_last_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_fsm_state1;
    static const sc_lv<24> ap_ST_fsm_state2;
    static const sc_lv<24> ap_ST_fsm_state3;
    static const sc_lv<24> ap_ST_fsm_state4;
    static const sc_lv<24> ap_ST_fsm_state5;
    static const sc_lv<24> ap_ST_fsm_state6;
    static const sc_lv<24> ap_ST_fsm_state7;
    static const sc_lv<24> ap_ST_fsm_state8;
    static const sc_lv<24> ap_ST_fsm_state9;
    static const sc_lv<24> ap_ST_fsm_state10;
    static const sc_lv<24> ap_ST_fsm_state11;
    static const sc_lv<24> ap_ST_fsm_state12;
    static const sc_lv<24> ap_ST_fsm_state13;
    static const sc_lv<24> ap_ST_fsm_state14;
    static const sc_lv<24> ap_ST_fsm_state15;
    static const sc_lv<24> ap_ST_fsm_state16;
    static const sc_lv<24> ap_ST_fsm_state17;
    static const sc_lv<24> ap_ST_fsm_state18;
    static const sc_lv<24> ap_ST_fsm_state19;
    static const sc_lv<24> ap_ST_fsm_state20;
    static const sc_lv<24> ap_ST_fsm_state21;
    static const sc_lv<24> ap_ST_fsm_state22;
    static const sc_lv<24> ap_ST_fsm_state23;
    static const sc_lv<24> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_block_state18_on_subcall_done();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_grp_myproject_fu_102_ap_done();
    void thread_ap_sync_grp_myproject_fu_102_ap_ready();
    void thread_grp_myproject_fu_102_ap_continue();
    void thread_grp_myproject_fu_102_ap_start();
    void thread_in_local_V_1_fu_132_p17();
    void thread_in_r_TDATA_blk_n();
    void thread_in_r_TREADY();
    void thread_in_r_TREADY_int();
    void thread_out_r_TDATA_blk_n();
    void thread_out_r_TDATA_int();
    void thread_out_r_TLAST_int();
    void thread_out_r_TVALID();
    void thread_out_r_TVALID_int();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
