// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V,
        data_1_V,
        data_2_V,
        data_3_V,
        data_4_V,
        data_5_V,
        data_6_V,
        data_7_V,
        data_8_V,
        data_9_V,
        data_10_V,
        data_11_V,
        data_12_V,
        data_13_V,
        data_14_V,
        data_15_V,
        data_16_V,
        data_17_V,
        data_18_V,
        data_19_V,
        data_20_V,
        data_21_V,
        data_22_V,
        data_23_V,
        data_24_V,
        data_25_V,
        data_26_V,
        data_27_V,
        data_28_V,
        data_29_V,
        data_30_V,
        data_31_V,
        res_0_V,
        res_0_V_ap_vld,
        res_1_V,
        res_1_V_ap_vld,
        res_2_V,
        res_2_V_ap_vld,
        res_3_V,
        res_3_V_ap_vld,
        res_4_V,
        res_4_V_ap_vld,
        res_5_V,
        res_5_V_ap_vld,
        res_6_V,
        res_6_V_ap_vld,
        res_7_V,
        res_7_V_ap_vld,
        res_8_V,
        res_8_V_ap_vld,
        res_9_V,
        res_9_V_ap_vld,
        res_10_V,
        res_10_V_ap_vld,
        res_11_V,
        res_11_V_ap_vld,
        res_12_V,
        res_12_V_ap_vld,
        res_13_V,
        res_13_V_ap_vld,
        res_14_V,
        res_14_V_ap_vld,
        res_15_V,
        res_15_V_ap_vld,
        res_16_V,
        res_16_V_ap_vld,
        res_17_V,
        res_17_V_ap_vld,
        res_18_V,
        res_18_V_ap_vld,
        res_19_V,
        res_19_V_ap_vld,
        res_20_V,
        res_20_V_ap_vld,
        res_21_V,
        res_21_V_ap_vld,
        res_22_V,
        res_22_V_ap_vld,
        res_23_V,
        res_23_V_ap_vld,
        res_24_V,
        res_24_V_ap_vld,
        res_25_V,
        res_25_V_ap_vld,
        res_26_V,
        res_26_V_ap_vld,
        res_27_V,
        res_27_V_ap_vld,
        res_28_V,
        res_28_V_ap_vld,
        res_29_V,
        res_29_V_ap_vld,
        res_30_V,
        res_30_V_ap_vld,
        res_31_V,
        res_31_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [5:0] data_0_V;
input  [5:0] data_1_V;
input  [5:0] data_2_V;
input  [5:0] data_3_V;
input  [5:0] data_4_V;
input  [5:0] data_5_V;
input  [5:0] data_6_V;
input  [5:0] data_7_V;
input  [5:0] data_8_V;
input  [5:0] data_9_V;
input  [5:0] data_10_V;
input  [5:0] data_11_V;
input  [5:0] data_12_V;
input  [5:0] data_13_V;
input  [5:0] data_14_V;
input  [5:0] data_15_V;
input  [5:0] data_16_V;
input  [5:0] data_17_V;
input  [5:0] data_18_V;
input  [5:0] data_19_V;
input  [5:0] data_20_V;
input  [5:0] data_21_V;
input  [5:0] data_22_V;
input  [5:0] data_23_V;
input  [5:0] data_24_V;
input  [5:0] data_25_V;
input  [5:0] data_26_V;
input  [5:0] data_27_V;
input  [5:0] data_28_V;
input  [5:0] data_29_V;
input  [5:0] data_30_V;
input  [5:0] data_31_V;
output  [15:0] res_0_V;
output   res_0_V_ap_vld;
output  [15:0] res_1_V;
output   res_1_V_ap_vld;
output  [15:0] res_2_V;
output   res_2_V_ap_vld;
output  [15:0] res_3_V;
output   res_3_V_ap_vld;
output  [15:0] res_4_V;
output   res_4_V_ap_vld;
output  [15:0] res_5_V;
output   res_5_V_ap_vld;
output  [15:0] res_6_V;
output   res_6_V_ap_vld;
output  [15:0] res_7_V;
output   res_7_V_ap_vld;
output  [15:0] res_8_V;
output   res_8_V_ap_vld;
output  [15:0] res_9_V;
output   res_9_V_ap_vld;
output  [15:0] res_10_V;
output   res_10_V_ap_vld;
output  [15:0] res_11_V;
output   res_11_V_ap_vld;
output  [15:0] res_12_V;
output   res_12_V_ap_vld;
output  [15:0] res_13_V;
output   res_13_V_ap_vld;
output  [15:0] res_14_V;
output   res_14_V_ap_vld;
output  [15:0] res_15_V;
output   res_15_V_ap_vld;
output  [15:0] res_16_V;
output   res_16_V_ap_vld;
output  [15:0] res_17_V;
output   res_17_V_ap_vld;
output  [15:0] res_18_V;
output   res_18_V_ap_vld;
output  [15:0] res_19_V;
output   res_19_V_ap_vld;
output  [15:0] res_20_V;
output   res_20_V_ap_vld;
output  [15:0] res_21_V;
output   res_21_V_ap_vld;
output  [15:0] res_22_V;
output   res_22_V_ap_vld;
output  [15:0] res_23_V;
output   res_23_V_ap_vld;
output  [15:0] res_24_V;
output   res_24_V_ap_vld;
output  [15:0] res_25_V;
output   res_25_V_ap_vld;
output  [15:0] res_26_V;
output   res_26_V_ap_vld;
output  [15:0] res_27_V;
output   res_27_V_ap_vld;
output  [15:0] res_28_V;
output   res_28_V_ap_vld;
output  [15:0] res_29_V;
output   res_29_V_ap_vld;
output  [15:0] res_30_V;
output   res_30_V_ap_vld;
output  [15:0] res_31_V;
output   res_31_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_0_V_ap_vld;
reg res_1_V_ap_vld;
reg res_2_V_ap_vld;
reg res_3_V_ap_vld;
reg res_4_V_ap_vld;
reg res_5_V_ap_vld;
reg res_6_V_ap_vld;
reg res_7_V_ap_vld;
reg res_8_V_ap_vld;
reg res_9_V_ap_vld;
reg res_10_V_ap_vld;
reg res_11_V_ap_vld;
reg res_12_V_ap_vld;
reg res_13_V_ap_vld;
reg res_14_V_ap_vld;
reg res_15_V_ap_vld;
reg res_16_V_ap_vld;
reg res_17_V_ap_vld;
reg res_18_V_ap_vld;
reg res_19_V_ap_vld;
reg res_20_V_ap_vld;
reg res_21_V_ap_vld;
reg res_22_V_ap_vld;
reg res_23_V_ap_vld;
reg res_24_V_ap_vld;
reg res_25_V_ap_vld;
reg res_26_V_ap_vld;
reg res_27_V_ap_vld;
reg res_28_V_ap_vld;
reg res_29_V_ap_vld;
reg res_30_V_ap_vld;
reg res_31_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln151_fu_1248_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] outidx_address0;
reg    outidx_ce0;
wire   [0:0] outidx_q0;
wire   [5:0] w8_V_address0;
reg    w8_V_ce0;
wire   [110:0] w8_V_q0;
reg   [31:0] in_index_0_i82_reg_722;
reg   [5:0] w_index81_reg_737;
reg   [15:0] acc_V_0_080_reg_766;
reg   [15:0] acc_V_1_078_reg_780;
reg   [15:0] acc_V_2_076_reg_794;
reg   [15:0] acc_V_3_074_reg_808;
reg   [15:0] acc_V_4_072_reg_822;
reg   [15:0] acc_V_5_070_reg_836;
reg   [15:0] acc_V_6_068_reg_850;
reg   [15:0] acc_V_7_066_reg_864;
reg   [15:0] acc_V_8_064_reg_878;
reg   [15:0] acc_V_9_062_reg_892;
reg   [15:0] acc_V_10_060_reg_906;
reg   [15:0] acc_V_11_058_reg_920;
reg   [15:0] acc_V_12_056_reg_934;
reg   [15:0] acc_V_13_054_reg_948;
reg   [15:0] acc_V_14_052_reg_962;
reg   [15:0] acc_V_15_050_reg_976;
reg   [15:0] acc_V_16_048_reg_990;
reg   [15:0] acc_V_17_046_reg_1004;
reg   [15:0] acc_V_18_044_reg_1018;
reg   [15:0] acc_V_19_042_reg_1032;
reg   [15:0] acc_V_20_040_reg_1046;
reg   [15:0] acc_V_21_038_reg_1060;
reg   [15:0] acc_V_22_036_reg_1074;
reg   [15:0] acc_V_23_034_reg_1088;
reg   [15:0] acc_V_24_032_reg_1102;
reg   [15:0] acc_V_25_030_reg_1116;
reg   [15:0] acc_V_26_028_reg_1130;
reg   [15:0] acc_V_27_026_reg_1144;
reg   [15:0] acc_V_28_024_reg_1158;
reg   [15:0] acc_V_29_022_reg_1172;
reg   [15:0] acc_V_30_020_reg_1186;
reg   [15:0] acc_V_31_018_reg_1200;
wire   [31:0] in_index_fu_1220_p2;
reg   [31:0] in_index_reg_2578;
wire   [0:0] icmp_ln168_fu_1236_p2;
reg   [0:0] icmp_ln168_reg_2583;
wire   [5:0] w_index_fu_1242_p2;
reg   [5:0] w_index_reg_2588;
reg   [0:0] icmp_ln151_reg_2593;
reg   [0:0] icmp_ln151_reg_2593_pp0_iter1_reg;
reg   [0:0] icmp_ln151_reg_2593_pp0_iter2_reg;
reg   [0:0] out_index_reg_2597;
reg   [0:0] out_index_reg_2597_pp0_iter2_reg;
wire  signed [6:0] tmp_1_fu_1354_p34;
reg  signed [6:0] tmp_1_reg_2649;
wire   [6:0] trunc_ln160_3_fu_1424_p1;
reg   [6:0] trunc_ln160_3_reg_2655;
reg   [6:0] tmp_3_reg_2660;
reg   [6:0] tmp_4_reg_2665;
reg   [6:0] tmp_5_reg_2670;
reg   [6:0] tmp_6_reg_2675;
reg   [6:0] tmp_7_reg_2680;
reg   [6:0] tmp_8_reg_2685;
reg   [6:0] tmp_9_reg_2690;
reg   [6:0] tmp_s_reg_2695;
reg   [6:0] tmp_10_reg_2700;
reg   [6:0] tmp_11_reg_2705;
reg   [6:0] tmp_12_reg_2710;
reg   [6:0] tmp_13_reg_2715;
reg   [6:0] tmp_14_reg_2720;
reg   [6:0] tmp_15_reg_2725;
reg   [5:0] tmp_16_reg_2730;
wire   [31:0] select_ln168_fu_1578_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [13:0] mul_ln1118_fu_1593_p2;
reg   [13:0] mul_ln1118_reg_2740;
wire   [13:0] mul_ln1118_5_fu_1602_p2;
reg   [13:0] mul_ln1118_5_reg_2745;
wire   [13:0] mul_ln1118_6_fu_1611_p2;
reg   [13:0] mul_ln1118_6_reg_2750;
wire   [13:0] mul_ln1118_7_fu_1620_p2;
reg   [13:0] mul_ln1118_7_reg_2755;
wire   [13:0] mul_ln1118_8_fu_1629_p2;
reg   [13:0] mul_ln1118_8_reg_2760;
wire   [13:0] mul_ln1118_9_fu_1638_p2;
reg   [13:0] mul_ln1118_9_reg_2765;
wire   [13:0] mul_ln1118_10_fu_1647_p2;
reg   [13:0] mul_ln1118_10_reg_2770;
wire   [13:0] mul_ln1118_11_fu_1656_p2;
reg   [13:0] mul_ln1118_11_reg_2775;
wire   [13:0] mul_ln1118_12_fu_1665_p2;
reg   [13:0] mul_ln1118_12_reg_2780;
wire   [13:0] mul_ln1118_13_fu_1674_p2;
reg   [13:0] mul_ln1118_13_reg_2785;
wire   [13:0] mul_ln1118_14_fu_1683_p2;
reg   [13:0] mul_ln1118_14_reg_2790;
wire   [13:0] mul_ln1118_15_fu_1692_p2;
reg   [13:0] mul_ln1118_15_reg_2795;
wire   [13:0] mul_ln1118_16_fu_1701_p2;
reg   [13:0] mul_ln1118_16_reg_2800;
wire   [13:0] mul_ln1118_17_fu_1710_p2;
reg   [13:0] mul_ln1118_17_reg_2805;
wire   [13:0] mul_ln1118_18_fu_1719_p2;
reg   [13:0] mul_ln1118_18_reg_2810;
wire   [12:0] mul_ln1118_19_fu_1728_p2;
reg   [12:0] mul_ln1118_19_reg_2815;
wire   [15:0] acc_1_V_1_fu_1760_p3;
reg    ap_enable_reg_pp0_iter3;
wire   [15:0] acc_1_V_2_fu_1768_p3;
wire   [15:0] acc_3_V_1_fu_1802_p3;
wire   [15:0] acc_3_V_2_fu_1810_p3;
wire   [15:0] acc_5_V_1_fu_1844_p3;
wire   [15:0] acc_5_V_2_fu_1852_p3;
wire   [15:0] acc_7_V_1_fu_1886_p3;
wire   [15:0] acc_7_V_2_fu_1894_p3;
wire   [15:0] acc_9_V_1_fu_1928_p3;
wire   [15:0] acc_9_V_2_fu_1936_p3;
wire   [15:0] acc_11_V_1_fu_1970_p3;
wire   [15:0] acc_11_V_2_fu_1978_p3;
wire   [15:0] acc_13_V_1_fu_2012_p3;
wire   [15:0] acc_13_V_2_fu_2020_p3;
wire   [15:0] acc_15_V_1_fu_2054_p3;
wire   [15:0] acc_15_V_2_fu_2062_p3;
wire   [15:0] acc_17_V_1_fu_2096_p3;
wire   [15:0] acc_17_V_2_fu_2104_p3;
wire   [15:0] acc_19_V_1_fu_2138_p3;
wire   [15:0] acc_19_V_2_fu_2146_p3;
wire   [15:0] acc_21_V_1_fu_2180_p3;
wire   [15:0] acc_21_V_2_fu_2188_p3;
wire   [15:0] acc_23_V_1_fu_2222_p3;
wire   [15:0] acc_23_V_2_fu_2230_p3;
wire   [15:0] acc_25_V_1_fu_2264_p3;
wire   [15:0] acc_25_V_2_fu_2272_p3;
wire   [15:0] acc_27_V_1_fu_2306_p3;
wire   [15:0] acc_27_V_2_fu_2314_p3;
wire   [15:0] acc_29_V_1_fu_2348_p3;
wire   [15:0] acc_29_V_2_fu_2356_p3;
wire   [15:0] acc_31_V_1_fu_2390_p3;
wire   [15:0] acc_31_V_2_fu_2398_p3;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] ap_phi_mux_in_index_0_i82_phi_fu_726_p6;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_w_index81_phi_fu_741_p6;
wire   [63:0] zext_ln155_fu_1214_p1;
reg    ap_block_pp0_stage0_01001;
wire   [26:0] tmp_516_fu_1226_p4;
wire   [6:0] tmp_1_fu_1354_p1;
wire   [6:0] tmp_1_fu_1354_p2;
wire   [6:0] tmp_1_fu_1354_p3;
wire   [6:0] tmp_1_fu_1354_p4;
wire   [6:0] tmp_1_fu_1354_p5;
wire   [6:0] tmp_1_fu_1354_p6;
wire   [6:0] tmp_1_fu_1354_p7;
wire   [6:0] tmp_1_fu_1354_p8;
wire   [6:0] tmp_1_fu_1354_p9;
wire   [6:0] tmp_1_fu_1354_p10;
wire   [6:0] tmp_1_fu_1354_p11;
wire   [6:0] tmp_1_fu_1354_p12;
wire   [6:0] tmp_1_fu_1354_p13;
wire   [6:0] tmp_1_fu_1354_p14;
wire   [6:0] tmp_1_fu_1354_p15;
wire   [6:0] tmp_1_fu_1354_p16;
wire   [6:0] tmp_1_fu_1354_p17;
wire   [6:0] tmp_1_fu_1354_p18;
wire   [6:0] tmp_1_fu_1354_p19;
wire   [6:0] tmp_1_fu_1354_p20;
wire   [6:0] tmp_1_fu_1354_p21;
wire   [6:0] tmp_1_fu_1354_p22;
wire   [6:0] tmp_1_fu_1354_p23;
wire   [6:0] tmp_1_fu_1354_p24;
wire   [6:0] tmp_1_fu_1354_p25;
wire   [6:0] tmp_1_fu_1354_p26;
wire   [6:0] tmp_1_fu_1354_p27;
wire   [6:0] tmp_1_fu_1354_p28;
wire   [6:0] tmp_1_fu_1354_p29;
wire   [6:0] tmp_1_fu_1354_p30;
wire   [6:0] tmp_1_fu_1354_p31;
wire   [6:0] tmp_1_fu_1354_p32;
wire   [4:0] tmp_1_fu_1354_p33;
wire  signed [6:0] mul_ln1118_fu_1593_p0;
wire  signed [13:0] sext_ln1116_fu_1584_p1;
wire  signed [6:0] mul_ln1118_fu_1593_p1;
wire  signed [6:0] mul_ln1118_5_fu_1602_p0;
wire  signed [6:0] mul_ln1118_5_fu_1602_p1;
wire  signed [6:0] mul_ln1118_6_fu_1611_p0;
wire  signed [6:0] mul_ln1118_6_fu_1611_p1;
wire  signed [6:0] mul_ln1118_7_fu_1620_p0;
wire  signed [6:0] mul_ln1118_7_fu_1620_p1;
wire  signed [6:0] mul_ln1118_8_fu_1629_p0;
wire  signed [6:0] mul_ln1118_8_fu_1629_p1;
wire  signed [6:0] mul_ln1118_9_fu_1638_p0;
wire  signed [6:0] mul_ln1118_9_fu_1638_p1;
wire  signed [6:0] mul_ln1118_10_fu_1647_p0;
wire  signed [6:0] mul_ln1118_10_fu_1647_p1;
wire  signed [6:0] mul_ln1118_11_fu_1656_p0;
wire  signed [6:0] mul_ln1118_11_fu_1656_p1;
wire  signed [6:0] mul_ln1118_12_fu_1665_p0;
wire  signed [6:0] mul_ln1118_12_fu_1665_p1;
wire  signed [6:0] mul_ln1118_13_fu_1674_p0;
wire  signed [6:0] mul_ln1118_13_fu_1674_p1;
wire  signed [6:0] mul_ln1118_14_fu_1683_p0;
wire  signed [6:0] mul_ln1118_14_fu_1683_p1;
wire  signed [6:0] mul_ln1118_15_fu_1692_p0;
wire  signed [6:0] mul_ln1118_15_fu_1692_p1;
wire  signed [6:0] mul_ln1118_16_fu_1701_p0;
wire  signed [6:0] mul_ln1118_16_fu_1701_p1;
wire  signed [6:0] mul_ln1118_17_fu_1710_p0;
wire  signed [6:0] mul_ln1118_17_fu_1710_p1;
wire  signed [6:0] mul_ln1118_18_fu_1719_p0;
wire  signed [6:0] mul_ln1118_18_fu_1719_p1;
wire  signed [6:0] mul_ln1118_19_fu_1728_p0;
wire  signed [5:0] mul_ln1118_19_fu_1728_p1;
wire   [11:0] trunc_ln6_fu_1734_p4;
wire   [15:0] select_ln1265_fu_1747_p3;
wire  signed [15:0] sext_ln708_fu_1743_p1;
wire   [15:0] acc_0_V_fu_1754_p2;
wire   [11:0] trunc_ln708_130_fu_1776_p4;
wire   [15:0] select_ln1265_1_fu_1789_p3;
wire  signed [15:0] sext_ln708_1_fu_1785_p1;
wire   [15:0] acc_2_V_fu_1796_p2;
wire   [11:0] trunc_ln708_131_fu_1818_p4;
wire   [15:0] select_ln1265_2_fu_1831_p3;
wire  signed [15:0] sext_ln708_2_fu_1827_p1;
wire   [15:0] acc_4_V_fu_1838_p2;
wire   [11:0] trunc_ln708_132_fu_1860_p4;
wire   [15:0] select_ln1265_3_fu_1873_p3;
wire  signed [15:0] sext_ln708_3_fu_1869_p1;
wire   [15:0] acc_6_V_fu_1880_p2;
wire   [11:0] trunc_ln708_133_fu_1902_p4;
wire   [15:0] select_ln1265_4_fu_1915_p3;
wire  signed [15:0] sext_ln708_4_fu_1911_p1;
wire   [15:0] acc_8_V_fu_1922_p2;
wire   [11:0] trunc_ln708_134_fu_1944_p4;
wire   [15:0] select_ln1265_5_fu_1957_p3;
wire  signed [15:0] sext_ln708_5_fu_1953_p1;
wire   [15:0] acc_10_V_fu_1964_p2;
wire   [11:0] trunc_ln708_135_fu_1986_p4;
wire   [15:0] select_ln1265_6_fu_1999_p3;
wire  signed [15:0] sext_ln708_6_fu_1995_p1;
wire   [15:0] acc_12_V_fu_2006_p2;
wire   [11:0] trunc_ln708_136_fu_2028_p4;
wire   [15:0] select_ln1265_7_fu_2041_p3;
wire  signed [15:0] sext_ln708_7_fu_2037_p1;
wire   [15:0] acc_14_V_fu_2048_p2;
wire   [11:0] trunc_ln708_137_fu_2070_p4;
wire   [15:0] select_ln1265_8_fu_2083_p3;
wire  signed [15:0] sext_ln708_8_fu_2079_p1;
wire   [15:0] acc_16_V_fu_2090_p2;
wire   [11:0] trunc_ln708_138_fu_2112_p4;
wire   [15:0] select_ln1265_9_fu_2125_p3;
wire  signed [15:0] sext_ln708_9_fu_2121_p1;
wire   [15:0] acc_18_V_fu_2132_p2;
wire   [11:0] trunc_ln708_139_fu_2154_p4;
wire   [15:0] select_ln1265_10_fu_2167_p3;
wire  signed [15:0] sext_ln708_10_fu_2163_p1;
wire   [15:0] acc_20_V_fu_2174_p2;
wire   [11:0] trunc_ln708_s_fu_2196_p4;
wire   [15:0] select_ln1265_11_fu_2209_p3;
wire  signed [15:0] sext_ln708_11_fu_2205_p1;
wire   [15:0] acc_22_V_fu_2216_p2;
wire   [11:0] trunc_ln708_140_fu_2238_p4;
wire   [15:0] select_ln1265_12_fu_2251_p3;
wire  signed [15:0] sext_ln708_12_fu_2247_p1;
wire   [15:0] acc_24_V_fu_2258_p2;
wire   [11:0] trunc_ln708_141_fu_2280_p4;
wire   [15:0] select_ln1265_13_fu_2293_p3;
wire  signed [15:0] sext_ln708_13_fu_2289_p1;
wire   [15:0] acc_26_V_fu_2300_p2;
wire   [11:0] trunc_ln708_142_fu_2322_p4;
wire   [15:0] select_ln1265_14_fu_2335_p3;
wire  signed [15:0] sext_ln708_14_fu_2331_p1;
wire   [15:0] acc_28_V_fu_2342_p2;
wire   [10:0] trunc_ln708_143_fu_2364_p4;
wire   [15:0] select_ln1265_15_fu_2377_p3;
wire  signed [15:0] sext_ln708_15_fu_2373_p1;
wire   [15:0] acc_30_V_fu_2384_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_463;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

dense_resource_oujbC #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

dense_resource_w8_V #(
    .DataWidth( 111 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w8_V_address0),
    .ce0(w8_V_ce0),
    .q0(w8_V_q0)
);

myproject_axi_muxkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 7 ),
    .din10_WIDTH( 7 ),
    .din11_WIDTH( 7 ),
    .din12_WIDTH( 7 ),
    .din13_WIDTH( 7 ),
    .din14_WIDTH( 7 ),
    .din15_WIDTH( 7 ),
    .din16_WIDTH( 7 ),
    .din17_WIDTH( 7 ),
    .din18_WIDTH( 7 ),
    .din19_WIDTH( 7 ),
    .din20_WIDTH( 7 ),
    .din21_WIDTH( 7 ),
    .din22_WIDTH( 7 ),
    .din23_WIDTH( 7 ),
    .din24_WIDTH( 7 ),
    .din25_WIDTH( 7 ),
    .din26_WIDTH( 7 ),
    .din27_WIDTH( 7 ),
    .din28_WIDTH( 7 ),
    .din29_WIDTH( 7 ),
    .din30_WIDTH( 7 ),
    .din31_WIDTH( 7 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
myproject_axi_muxkbM_U398(
    .din0(tmp_1_fu_1354_p1),
    .din1(tmp_1_fu_1354_p2),
    .din2(tmp_1_fu_1354_p3),
    .din3(tmp_1_fu_1354_p4),
    .din4(tmp_1_fu_1354_p5),
    .din5(tmp_1_fu_1354_p6),
    .din6(tmp_1_fu_1354_p7),
    .din7(tmp_1_fu_1354_p8),
    .din8(tmp_1_fu_1354_p9),
    .din9(tmp_1_fu_1354_p10),
    .din10(tmp_1_fu_1354_p11),
    .din11(tmp_1_fu_1354_p12),
    .din12(tmp_1_fu_1354_p13),
    .din13(tmp_1_fu_1354_p14),
    .din14(tmp_1_fu_1354_p15),
    .din15(tmp_1_fu_1354_p16),
    .din16(tmp_1_fu_1354_p17),
    .din17(tmp_1_fu_1354_p18),
    .din18(tmp_1_fu_1354_p19),
    .din19(tmp_1_fu_1354_p20),
    .din20(tmp_1_fu_1354_p21),
    .din21(tmp_1_fu_1354_p22),
    .din22(tmp_1_fu_1354_p23),
    .din23(tmp_1_fu_1354_p24),
    .din24(tmp_1_fu_1354_p25),
    .din25(tmp_1_fu_1354_p26),
    .din26(tmp_1_fu_1354_p27),
    .din27(tmp_1_fu_1354_p28),
    .din28(tmp_1_fu_1354_p29),
    .din29(tmp_1_fu_1354_p30),
    .din30(tmp_1_fu_1354_p31),
    .din31(tmp_1_fu_1354_p32),
    .din32(tmp_1_fu_1354_p33),
    .dout(tmp_1_fu_1354_p34)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_0_080_reg_766 <= acc_1_V_2_fu_1768_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_0_080_reg_766 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_10_060_reg_906 <= acc_11_V_2_fu_1978_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_10_060_reg_906 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_11_058_reg_920 <= acc_11_V_1_fu_1970_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_11_058_reg_920 <= 16'd192;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_12_056_reg_934 <= acc_13_V_2_fu_2020_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_12_056_reg_934 <= 16'd65408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_13_054_reg_948 <= acc_13_V_1_fu_2012_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_13_054_reg_948 <= 16'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_14_052_reg_962 <= acc_15_V_2_fu_2062_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_14_052_reg_962 <= 16'd352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_15_050_reg_976 <= acc_15_V_1_fu_2054_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_15_050_reg_976 <= 16'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_16_048_reg_990 <= acc_17_V_2_fu_2104_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_16_048_reg_990 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_17_046_reg_1004 <= acc_17_V_1_fu_2096_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_17_046_reg_1004 <= 16'd96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_18_044_reg_1018 <= acc_19_V_2_fu_2146_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_18_044_reg_1018 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_19_042_reg_1032 <= acc_19_V_1_fu_2138_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_19_042_reg_1032 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_1_078_reg_780 <= acc_1_V_1_fu_1760_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1_078_reg_780 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_20_040_reg_1046 <= acc_21_V_2_fu_2188_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_20_040_reg_1046 <= 16'd64;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_21_038_reg_1060 <= acc_21_V_1_fu_2180_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_21_038_reg_1060 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_22_036_reg_1074 <= acc_23_V_2_fu_2230_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_22_036_reg_1074 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_23_034_reg_1088 <= acc_23_V_1_fu_2222_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_23_034_reg_1088 <= 16'd288;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_24_032_reg_1102 <= acc_25_V_2_fu_2272_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_24_032_reg_1102 <= 16'd65344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_25_030_reg_1116 <= acc_25_V_1_fu_2264_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_25_030_reg_1116 <= 16'd96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_26_028_reg_1130 <= acc_27_V_2_fu_2314_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_26_028_reg_1130 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_27_026_reg_1144 <= acc_27_V_1_fu_2306_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_27_026_reg_1144 <= 16'd192;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_28_024_reg_1158 <= acc_29_V_2_fu_2356_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_28_024_reg_1158 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_29_022_reg_1172 <= acc_29_V_1_fu_2348_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_29_022_reg_1172 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_2_076_reg_794 <= acc_3_V_2_fu_1810_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_2_076_reg_794 <= 16'd256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_30_020_reg_1186 <= acc_31_V_2_fu_2398_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_30_020_reg_1186 <= 16'd65472;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_31_018_reg_1200 <= acc_31_V_1_fu_2390_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_31_018_reg_1200 <= 16'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_3_074_reg_808 <= acc_3_V_1_fu_1802_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_3_074_reg_808 <= 16'd96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_4_072_reg_822 <= acc_5_V_2_fu_1852_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_4_072_reg_822 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_5_070_reg_836 <= acc_5_V_1_fu_1844_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_5_070_reg_836 <= 16'd96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_6_068_reg_850 <= acc_7_V_2_fu_1894_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_6_068_reg_850 <= 16'd65504;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_7_066_reg_864 <= acc_7_V_1_fu_1886_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_7_066_reg_864 <= 16'd96;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_8_064_reg_878 <= acc_9_V_2_fu_1936_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_8_064_reg_878 <= 16'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acc_V_9_062_reg_892 <= acc_9_V_1_fu_1928_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_9_062_reg_892 <= 16'd65440;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_0_i82_reg_722 <= select_ln168_fu_1578_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i82_reg_722 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index81_reg_737 <= w_index_reg_2588;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index81_reg_737 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln151_reg_2593 <= icmp_ln151_fu_1248_p2;
        icmp_ln151_reg_2593_pp0_iter1_reg <= icmp_ln151_reg_2593;
        icmp_ln168_reg_2583 <= icmp_ln168_fu_1236_p2;
        in_index_reg_2578 <= in_index_fu_1220_p2;
        out_index_reg_2597 <= outidx_q0;
        tmp_10_reg_2700 <= {{w8_V_q0[69:63]}};
        tmp_11_reg_2705 <= {{w8_V_q0[76:70]}};
        tmp_12_reg_2710 <= {{w8_V_q0[83:77]}};
        tmp_13_reg_2715 <= {{w8_V_q0[90:84]}};
        tmp_14_reg_2720 <= {{w8_V_q0[97:91]}};
        tmp_15_reg_2725 <= {{w8_V_q0[104:98]}};
        tmp_16_reg_2730 <= {{w8_V_q0[110:105]}};
        tmp_1_reg_2649 <= tmp_1_fu_1354_p34;
        tmp_3_reg_2660 <= {{w8_V_q0[13:7]}};
        tmp_4_reg_2665 <= {{w8_V_q0[20:14]}};
        tmp_5_reg_2670 <= {{w8_V_q0[27:21]}};
        tmp_6_reg_2675 <= {{w8_V_q0[34:28]}};
        tmp_7_reg_2680 <= {{w8_V_q0[41:35]}};
        tmp_8_reg_2685 <= {{w8_V_q0[48:42]}};
        tmp_9_reg_2690 <= {{w8_V_q0[55:49]}};
        tmp_s_reg_2695 <= {{w8_V_q0[62:56]}};
        trunc_ln160_3_reg_2655 <= trunc_ln160_3_fu_1424_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln151_reg_2593_pp0_iter2_reg <= icmp_ln151_reg_2593_pp0_iter1_reg;
        mul_ln1118_10_reg_2770 <= mul_ln1118_10_fu_1647_p2;
        mul_ln1118_11_reg_2775 <= mul_ln1118_11_fu_1656_p2;
        mul_ln1118_12_reg_2780 <= mul_ln1118_12_fu_1665_p2;
        mul_ln1118_13_reg_2785 <= mul_ln1118_13_fu_1674_p2;
        mul_ln1118_14_reg_2790 <= mul_ln1118_14_fu_1683_p2;
        mul_ln1118_15_reg_2795 <= mul_ln1118_15_fu_1692_p2;
        mul_ln1118_16_reg_2800 <= mul_ln1118_16_fu_1701_p2;
        mul_ln1118_17_reg_2805 <= mul_ln1118_17_fu_1710_p2;
        mul_ln1118_18_reg_2810 <= mul_ln1118_18_fu_1719_p2;
        mul_ln1118_19_reg_2815 <= mul_ln1118_19_fu_1728_p2;
        mul_ln1118_5_reg_2745 <= mul_ln1118_5_fu_1602_p2;
        mul_ln1118_6_reg_2750 <= mul_ln1118_6_fu_1611_p2;
        mul_ln1118_7_reg_2755 <= mul_ln1118_7_fu_1620_p2;
        mul_ln1118_8_reg_2760 <= mul_ln1118_8_fu_1629_p2;
        mul_ln1118_9_reg_2765 <= mul_ln1118_9_fu_1638_p2;
        mul_ln1118_reg_2740 <= mul_ln1118_fu_1593_p2;
        out_index_reg_2597_pp0_iter2_reg <= out_index_reg_2597;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_2588 <= w_index_fu_1242_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_463)) begin
        if ((icmp_ln151_reg_2593 == 1'd1)) begin
            ap_phi_mux_in_index_0_i82_phi_fu_726_p6 = 32'd0;
        end else if ((icmp_ln151_reg_2593 == 1'd0)) begin
            ap_phi_mux_in_index_0_i82_phi_fu_726_p6 = select_ln168_fu_1578_p3;
        end else begin
            ap_phi_mux_in_index_0_i82_phi_fu_726_p6 = in_index_0_i82_reg_722;
        end
    end else begin
        ap_phi_mux_in_index_0_i82_phi_fu_726_p6 = in_index_0_i82_reg_722;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_463)) begin
        if ((icmp_ln151_reg_2593 == 1'd1)) begin
            ap_phi_mux_w_index81_phi_fu_741_p6 = 6'd0;
        end else if ((icmp_ln151_reg_2593 == 1'd0)) begin
            ap_phi_mux_w_index81_phi_fu_741_p6 = w_index_reg_2588;
        end else begin
            ap_phi_mux_w_index81_phi_fu_741_p6 = w_index81_reg_737;
        end
    end else begin
        ap_phi_mux_w_index81_phi_fu_741_p6 = w_index81_reg_737;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_fu_1248_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_0_V_ap_vld = 1'b1;
    end else begin
        res_0_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_10_V_ap_vld = 1'b1;
    end else begin
        res_10_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_11_V_ap_vld = 1'b1;
    end else begin
        res_11_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_12_V_ap_vld = 1'b1;
    end else begin
        res_12_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_13_V_ap_vld = 1'b1;
    end else begin
        res_13_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_14_V_ap_vld = 1'b1;
    end else begin
        res_14_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_15_V_ap_vld = 1'b1;
    end else begin
        res_15_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_16_V_ap_vld = 1'b1;
    end else begin
        res_16_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_17_V_ap_vld = 1'b1;
    end else begin
        res_17_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_18_V_ap_vld = 1'b1;
    end else begin
        res_18_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_19_V_ap_vld = 1'b1;
    end else begin
        res_19_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_1_V_ap_vld = 1'b1;
    end else begin
        res_1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_20_V_ap_vld = 1'b1;
    end else begin
        res_20_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_21_V_ap_vld = 1'b1;
    end else begin
        res_21_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_22_V_ap_vld = 1'b1;
    end else begin
        res_22_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_23_V_ap_vld = 1'b1;
    end else begin
        res_23_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_24_V_ap_vld = 1'b1;
    end else begin
        res_24_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_25_V_ap_vld = 1'b1;
    end else begin
        res_25_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_26_V_ap_vld = 1'b1;
    end else begin
        res_26_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_27_V_ap_vld = 1'b1;
    end else begin
        res_27_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_28_V_ap_vld = 1'b1;
    end else begin
        res_28_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_29_V_ap_vld = 1'b1;
    end else begin
        res_29_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_2_V_ap_vld = 1'b1;
    end else begin
        res_2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_30_V_ap_vld = 1'b1;
    end else begin
        res_30_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_31_V_ap_vld = 1'b1;
    end else begin
        res_31_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_3_V_ap_vld = 1'b1;
    end else begin
        res_3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_4_V_ap_vld = 1'b1;
    end else begin
        res_4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_5_V_ap_vld = 1'b1;
    end else begin
        res_5_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_6_V_ap_vld = 1'b1;
    end else begin
        res_6_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_7_V_ap_vld = 1'b1;
    end else begin
        res_7_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_8_V_ap_vld = 1'b1;
    end else begin
        res_8_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_2593_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_9_V_ap_vld = 1'b1;
    end else begin
        res_9_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w8_V_ce0 = 1'b1;
    end else begin
        w8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1754_p2 = ($signed(select_ln1265_fu_1747_p3) + $signed(sext_ln708_fu_1743_p1));

assign acc_10_V_fu_1964_p2 = ($signed(select_ln1265_5_fu_1957_p3) + $signed(sext_ln708_5_fu_1953_p1));

assign acc_11_V_1_fu_1970_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_10_V_fu_1964_p2 : acc_V_11_058_reg_920);

assign acc_11_V_2_fu_1978_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_10_060_reg_906 : acc_10_V_fu_1964_p2);

assign acc_12_V_fu_2006_p2 = ($signed(select_ln1265_6_fu_1999_p3) + $signed(sext_ln708_6_fu_1995_p1));

assign acc_13_V_1_fu_2012_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_12_V_fu_2006_p2 : acc_V_13_054_reg_948);

assign acc_13_V_2_fu_2020_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_12_056_reg_934 : acc_12_V_fu_2006_p2);

assign acc_14_V_fu_2048_p2 = ($signed(select_ln1265_7_fu_2041_p3) + $signed(sext_ln708_7_fu_2037_p1));

assign acc_15_V_1_fu_2054_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_14_V_fu_2048_p2 : acc_V_15_050_reg_976);

assign acc_15_V_2_fu_2062_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_14_052_reg_962 : acc_14_V_fu_2048_p2);

assign acc_16_V_fu_2090_p2 = ($signed(select_ln1265_8_fu_2083_p3) + $signed(sext_ln708_8_fu_2079_p1));

assign acc_17_V_1_fu_2096_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_16_V_fu_2090_p2 : acc_V_17_046_reg_1004);

assign acc_17_V_2_fu_2104_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_16_048_reg_990 : acc_16_V_fu_2090_p2);

assign acc_18_V_fu_2132_p2 = ($signed(select_ln1265_9_fu_2125_p3) + $signed(sext_ln708_9_fu_2121_p1));

assign acc_19_V_1_fu_2138_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_18_V_fu_2132_p2 : acc_V_19_042_reg_1032);

assign acc_19_V_2_fu_2146_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_18_044_reg_1018 : acc_18_V_fu_2132_p2);

assign acc_1_V_1_fu_1760_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_0_V_fu_1754_p2 : acc_V_1_078_reg_780);

assign acc_1_V_2_fu_1768_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_0_080_reg_766 : acc_0_V_fu_1754_p2);

assign acc_20_V_fu_2174_p2 = ($signed(select_ln1265_10_fu_2167_p3) + $signed(sext_ln708_10_fu_2163_p1));

assign acc_21_V_1_fu_2180_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_20_V_fu_2174_p2 : acc_V_21_038_reg_1060);

assign acc_21_V_2_fu_2188_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_20_040_reg_1046 : acc_20_V_fu_2174_p2);

assign acc_22_V_fu_2216_p2 = ($signed(select_ln1265_11_fu_2209_p3) + $signed(sext_ln708_11_fu_2205_p1));

assign acc_23_V_1_fu_2222_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_22_V_fu_2216_p2 : acc_V_23_034_reg_1088);

assign acc_23_V_2_fu_2230_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_22_036_reg_1074 : acc_22_V_fu_2216_p2);

assign acc_24_V_fu_2258_p2 = ($signed(select_ln1265_12_fu_2251_p3) + $signed(sext_ln708_12_fu_2247_p1));

assign acc_25_V_1_fu_2264_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_24_V_fu_2258_p2 : acc_V_25_030_reg_1116);

assign acc_25_V_2_fu_2272_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_24_032_reg_1102 : acc_24_V_fu_2258_p2);

assign acc_26_V_fu_2300_p2 = ($signed(select_ln1265_13_fu_2293_p3) + $signed(sext_ln708_13_fu_2289_p1));

assign acc_27_V_1_fu_2306_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_26_V_fu_2300_p2 : acc_V_27_026_reg_1144);

assign acc_27_V_2_fu_2314_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_26_028_reg_1130 : acc_26_V_fu_2300_p2);

assign acc_28_V_fu_2342_p2 = ($signed(select_ln1265_14_fu_2335_p3) + $signed(sext_ln708_14_fu_2331_p1));

assign acc_29_V_1_fu_2348_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_28_V_fu_2342_p2 : acc_V_29_022_reg_1172);

assign acc_29_V_2_fu_2356_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_28_024_reg_1158 : acc_28_V_fu_2342_p2);

assign acc_2_V_fu_1796_p2 = ($signed(select_ln1265_1_fu_1789_p3) + $signed(sext_ln708_1_fu_1785_p1));

assign acc_30_V_fu_2384_p2 = ($signed(select_ln1265_15_fu_2377_p3) + $signed(sext_ln708_15_fu_2373_p1));

assign acc_31_V_1_fu_2390_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_30_V_fu_2384_p2 : acc_V_31_018_reg_1200);

assign acc_31_V_2_fu_2398_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_30_020_reg_1186 : acc_30_V_fu_2384_p2);

assign acc_3_V_1_fu_1802_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_2_V_fu_1796_p2 : acc_V_3_074_reg_808);

assign acc_3_V_2_fu_1810_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_2_076_reg_794 : acc_2_V_fu_1796_p2);

assign acc_4_V_fu_1838_p2 = ($signed(select_ln1265_2_fu_1831_p3) + $signed(sext_ln708_2_fu_1827_p1));

assign acc_5_V_1_fu_1844_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_4_V_fu_1838_p2 : acc_V_5_070_reg_836);

assign acc_5_V_2_fu_1852_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_4_072_reg_822 : acc_4_V_fu_1838_p2);

assign acc_6_V_fu_1880_p2 = ($signed(select_ln1265_3_fu_1873_p3) + $signed(sext_ln708_3_fu_1869_p1));

assign acc_7_V_1_fu_1886_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_6_V_fu_1880_p2 : acc_V_7_066_reg_864);

assign acc_7_V_2_fu_1894_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_6_068_reg_850 : acc_6_V_fu_1880_p2);

assign acc_8_V_fu_1922_p2 = ($signed(select_ln1265_4_fu_1915_p3) + $signed(sext_ln708_4_fu_1911_p1));

assign acc_9_V_1_fu_1928_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_8_V_fu_1922_p2 : acc_V_9_062_reg_892);

assign acc_9_V_2_fu_1936_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_8_064_reg_878 : acc_8_V_fu_1922_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_463 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign icmp_ln151_fu_1248_p2 = ((ap_phi_mux_w_index81_phi_fu_741_p6 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1236_p2 = (($signed(tmp_516_fu_1226_p4) > $signed(27'd0)) ? 1'b1 : 1'b0);

assign in_index_fu_1220_p2 = (32'd1 + ap_phi_mux_in_index_0_i82_phi_fu_726_p6);

assign mul_ln1118_10_fu_1647_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_10_fu_1647_p1 = tmp_8_reg_2685;

assign mul_ln1118_10_fu_1647_p2 = ($signed(mul_ln1118_10_fu_1647_p0) * $signed(mul_ln1118_10_fu_1647_p1));

assign mul_ln1118_11_fu_1656_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_11_fu_1656_p1 = tmp_9_reg_2690;

assign mul_ln1118_11_fu_1656_p2 = ($signed(mul_ln1118_11_fu_1656_p0) * $signed(mul_ln1118_11_fu_1656_p1));

assign mul_ln1118_12_fu_1665_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_12_fu_1665_p1 = tmp_s_reg_2695;

assign mul_ln1118_12_fu_1665_p2 = ($signed(mul_ln1118_12_fu_1665_p0) * $signed(mul_ln1118_12_fu_1665_p1));

assign mul_ln1118_13_fu_1674_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_13_fu_1674_p1 = tmp_10_reg_2700;

assign mul_ln1118_13_fu_1674_p2 = ($signed(mul_ln1118_13_fu_1674_p0) * $signed(mul_ln1118_13_fu_1674_p1));

assign mul_ln1118_14_fu_1683_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_14_fu_1683_p1 = tmp_11_reg_2705;

assign mul_ln1118_14_fu_1683_p2 = ($signed(mul_ln1118_14_fu_1683_p0) * $signed(mul_ln1118_14_fu_1683_p1));

assign mul_ln1118_15_fu_1692_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_15_fu_1692_p1 = tmp_12_reg_2710;

assign mul_ln1118_15_fu_1692_p2 = ($signed(mul_ln1118_15_fu_1692_p0) * $signed(mul_ln1118_15_fu_1692_p1));

assign mul_ln1118_16_fu_1701_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_16_fu_1701_p1 = tmp_13_reg_2715;

assign mul_ln1118_16_fu_1701_p2 = ($signed(mul_ln1118_16_fu_1701_p0) * $signed(mul_ln1118_16_fu_1701_p1));

assign mul_ln1118_17_fu_1710_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_17_fu_1710_p1 = tmp_14_reg_2720;

assign mul_ln1118_17_fu_1710_p2 = ($signed(mul_ln1118_17_fu_1710_p0) * $signed(mul_ln1118_17_fu_1710_p1));

assign mul_ln1118_18_fu_1719_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_18_fu_1719_p1 = tmp_15_reg_2725;

assign mul_ln1118_18_fu_1719_p2 = ($signed(mul_ln1118_18_fu_1719_p0) * $signed(mul_ln1118_18_fu_1719_p1));

assign mul_ln1118_19_fu_1728_p0 = tmp_1_reg_2649;

assign mul_ln1118_19_fu_1728_p1 = tmp_16_reg_2730;

assign mul_ln1118_19_fu_1728_p2 = ($signed(mul_ln1118_19_fu_1728_p0) * $signed(mul_ln1118_19_fu_1728_p1));

assign mul_ln1118_5_fu_1602_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_5_fu_1602_p1 = tmp_3_reg_2660;

assign mul_ln1118_5_fu_1602_p2 = ($signed(mul_ln1118_5_fu_1602_p0) * $signed(mul_ln1118_5_fu_1602_p1));

assign mul_ln1118_6_fu_1611_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_6_fu_1611_p1 = tmp_4_reg_2665;

assign mul_ln1118_6_fu_1611_p2 = ($signed(mul_ln1118_6_fu_1611_p0) * $signed(mul_ln1118_6_fu_1611_p1));

assign mul_ln1118_7_fu_1620_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_7_fu_1620_p1 = tmp_5_reg_2670;

assign mul_ln1118_7_fu_1620_p2 = ($signed(mul_ln1118_7_fu_1620_p0) * $signed(mul_ln1118_7_fu_1620_p1));

assign mul_ln1118_8_fu_1629_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_8_fu_1629_p1 = tmp_6_reg_2675;

assign mul_ln1118_8_fu_1629_p2 = ($signed(mul_ln1118_8_fu_1629_p0) * $signed(mul_ln1118_8_fu_1629_p1));

assign mul_ln1118_9_fu_1638_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_9_fu_1638_p1 = tmp_7_reg_2680;

assign mul_ln1118_9_fu_1638_p2 = ($signed(mul_ln1118_9_fu_1638_p0) * $signed(mul_ln1118_9_fu_1638_p1));

assign mul_ln1118_fu_1593_p0 = sext_ln1116_fu_1584_p1;

assign mul_ln1118_fu_1593_p1 = trunc_ln160_3_reg_2655;

assign mul_ln1118_fu_1593_p2 = ($signed(mul_ln1118_fu_1593_p0) * $signed(mul_ln1118_fu_1593_p1));

assign outidx_address0 = zext_ln155_fu_1214_p1;

assign res_0_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_0_080_reg_766 : acc_0_V_fu_1754_p2);

assign res_10_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_10_060_reg_906 : acc_10_V_fu_1964_p2);

assign res_11_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_10_V_fu_1964_p2 : acc_V_11_058_reg_920);

assign res_12_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_12_056_reg_934 : acc_12_V_fu_2006_p2);

assign res_13_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_12_V_fu_2006_p2 : acc_V_13_054_reg_948);

assign res_14_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_14_052_reg_962 : acc_14_V_fu_2048_p2);

assign res_15_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_14_V_fu_2048_p2 : acc_V_15_050_reg_976);

assign res_16_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_16_048_reg_990 : acc_16_V_fu_2090_p2);

assign res_17_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_16_V_fu_2090_p2 : acc_V_17_046_reg_1004);

assign res_18_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_18_044_reg_1018 : acc_18_V_fu_2132_p2);

assign res_19_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_18_V_fu_2132_p2 : acc_V_19_042_reg_1032);

assign res_1_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_0_V_fu_1754_p2 : acc_V_1_078_reg_780);

assign res_20_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_20_040_reg_1046 : acc_20_V_fu_2174_p2);

assign res_21_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_20_V_fu_2174_p2 : acc_V_21_038_reg_1060);

assign res_22_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_22_036_reg_1074 : acc_22_V_fu_2216_p2);

assign res_23_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_22_V_fu_2216_p2 : acc_V_23_034_reg_1088);

assign res_24_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_24_032_reg_1102 : acc_24_V_fu_2258_p2);

assign res_25_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_24_V_fu_2258_p2 : acc_V_25_030_reg_1116);

assign res_26_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_26_028_reg_1130 : acc_26_V_fu_2300_p2);

assign res_27_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_26_V_fu_2300_p2 : acc_V_27_026_reg_1144);

assign res_28_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_28_024_reg_1158 : acc_28_V_fu_2342_p2);

assign res_29_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_28_V_fu_2342_p2 : acc_V_29_022_reg_1172);

assign res_2_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_2_076_reg_794 : acc_2_V_fu_1796_p2);

assign res_30_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_30_020_reg_1186 : acc_30_V_fu_2384_p2);

assign res_31_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_30_V_fu_2384_p2 : acc_V_31_018_reg_1200);

assign res_3_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_2_V_fu_1796_p2 : acc_V_3_074_reg_808);

assign res_4_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_4_072_reg_822 : acc_4_V_fu_1838_p2);

assign res_5_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_4_V_fu_1838_p2 : acc_V_5_070_reg_836);

assign res_6_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_6_068_reg_850 : acc_6_V_fu_1880_p2);

assign res_7_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_6_V_fu_1880_p2 : acc_V_7_066_reg_864);

assign res_8_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_8_064_reg_878 : acc_8_V_fu_1922_p2);

assign res_9_V = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_8_V_fu_1922_p2 : acc_V_9_062_reg_892);

assign select_ln1265_10_fu_2167_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_21_038_reg_1060 : acc_V_20_040_reg_1046);

assign select_ln1265_11_fu_2209_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_23_034_reg_1088 : acc_V_22_036_reg_1074);

assign select_ln1265_12_fu_2251_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_25_030_reg_1116 : acc_V_24_032_reg_1102);

assign select_ln1265_13_fu_2293_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_27_026_reg_1144 : acc_V_26_028_reg_1130);

assign select_ln1265_14_fu_2335_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_29_022_reg_1172 : acc_V_28_024_reg_1158);

assign select_ln1265_15_fu_2377_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_31_018_reg_1200 : acc_V_30_020_reg_1186);

assign select_ln1265_1_fu_1789_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_3_074_reg_808 : acc_V_2_076_reg_794);

assign select_ln1265_2_fu_1831_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_5_070_reg_836 : acc_V_4_072_reg_822);

assign select_ln1265_3_fu_1873_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_7_066_reg_864 : acc_V_6_068_reg_850);

assign select_ln1265_4_fu_1915_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_9_062_reg_892 : acc_V_8_064_reg_878);

assign select_ln1265_5_fu_1957_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_11_058_reg_920 : acc_V_10_060_reg_906);

assign select_ln1265_6_fu_1999_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_13_054_reg_948 : acc_V_12_056_reg_934);

assign select_ln1265_7_fu_2041_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_15_050_reg_976 : acc_V_14_052_reg_962);

assign select_ln1265_8_fu_2083_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_17_046_reg_1004 : acc_V_16_048_reg_990);

assign select_ln1265_9_fu_2125_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_19_042_reg_1032 : acc_V_18_044_reg_1018);

assign select_ln1265_fu_1747_p3 = ((out_index_reg_2597_pp0_iter2_reg[0:0] === 1'b1) ? acc_V_1_078_reg_780 : acc_V_0_080_reg_766);

assign select_ln168_fu_1578_p3 = ((icmp_ln168_reg_2583[0:0] === 1'b1) ? 32'd0 : in_index_reg_2578);

assign sext_ln1116_fu_1584_p1 = tmp_1_reg_2649;

assign sext_ln708_10_fu_2163_p1 = $signed(trunc_ln708_139_fu_2154_p4);

assign sext_ln708_11_fu_2205_p1 = $signed(trunc_ln708_s_fu_2196_p4);

assign sext_ln708_12_fu_2247_p1 = $signed(trunc_ln708_140_fu_2238_p4);

assign sext_ln708_13_fu_2289_p1 = $signed(trunc_ln708_141_fu_2280_p4);

assign sext_ln708_14_fu_2331_p1 = $signed(trunc_ln708_142_fu_2322_p4);

assign sext_ln708_15_fu_2373_p1 = $signed(trunc_ln708_143_fu_2364_p4);

assign sext_ln708_1_fu_1785_p1 = $signed(trunc_ln708_130_fu_1776_p4);

assign sext_ln708_2_fu_1827_p1 = $signed(trunc_ln708_131_fu_1818_p4);

assign sext_ln708_3_fu_1869_p1 = $signed(trunc_ln708_132_fu_1860_p4);

assign sext_ln708_4_fu_1911_p1 = $signed(trunc_ln708_133_fu_1902_p4);

assign sext_ln708_5_fu_1953_p1 = $signed(trunc_ln708_134_fu_1944_p4);

assign sext_ln708_6_fu_1995_p1 = $signed(trunc_ln708_135_fu_1986_p4);

assign sext_ln708_7_fu_2037_p1 = $signed(trunc_ln708_136_fu_2028_p4);

assign sext_ln708_8_fu_2079_p1 = $signed(trunc_ln708_137_fu_2070_p4);

assign sext_ln708_9_fu_2121_p1 = $signed(trunc_ln708_138_fu_2112_p4);

assign sext_ln708_fu_1743_p1 = $signed(trunc_ln6_fu_1734_p4);

assign tmp_1_fu_1354_p1 = data_0_V;

assign tmp_1_fu_1354_p10 = data_9_V;

assign tmp_1_fu_1354_p11 = data_10_V;

assign tmp_1_fu_1354_p12 = data_11_V;

assign tmp_1_fu_1354_p13 = data_12_V;

assign tmp_1_fu_1354_p14 = data_13_V;

assign tmp_1_fu_1354_p15 = data_14_V;

assign tmp_1_fu_1354_p16 = data_15_V;

assign tmp_1_fu_1354_p17 = data_16_V;

assign tmp_1_fu_1354_p18 = data_17_V;

assign tmp_1_fu_1354_p19 = data_18_V;

assign tmp_1_fu_1354_p2 = data_1_V;

assign tmp_1_fu_1354_p20 = data_19_V;

assign tmp_1_fu_1354_p21 = data_20_V;

assign tmp_1_fu_1354_p22 = data_21_V;

assign tmp_1_fu_1354_p23 = data_22_V;

assign tmp_1_fu_1354_p24 = data_23_V;

assign tmp_1_fu_1354_p25 = data_24_V;

assign tmp_1_fu_1354_p26 = data_25_V;

assign tmp_1_fu_1354_p27 = data_26_V;

assign tmp_1_fu_1354_p28 = data_27_V;

assign tmp_1_fu_1354_p29 = data_28_V;

assign tmp_1_fu_1354_p3 = data_2_V;

assign tmp_1_fu_1354_p30 = data_29_V;

assign tmp_1_fu_1354_p31 = data_30_V;

assign tmp_1_fu_1354_p32 = data_31_V;

assign tmp_1_fu_1354_p33 = in_index_0_i82_reg_722[4:0];

assign tmp_1_fu_1354_p4 = data_3_V;

assign tmp_1_fu_1354_p5 = data_4_V;

assign tmp_1_fu_1354_p6 = data_5_V;

assign tmp_1_fu_1354_p7 = data_6_V;

assign tmp_1_fu_1354_p8 = data_7_V;

assign tmp_1_fu_1354_p9 = data_8_V;

assign tmp_516_fu_1226_p4 = {{in_index_fu_1220_p2[31:5]}};

assign trunc_ln160_3_fu_1424_p1 = w8_V_q0[6:0];

assign trunc_ln6_fu_1734_p4 = {{mul_ln1118_reg_2740[13:2]}};

assign trunc_ln708_130_fu_1776_p4 = {{mul_ln1118_5_reg_2745[13:2]}};

assign trunc_ln708_131_fu_1818_p4 = {{mul_ln1118_6_reg_2750[13:2]}};

assign trunc_ln708_132_fu_1860_p4 = {{mul_ln1118_7_reg_2755[13:2]}};

assign trunc_ln708_133_fu_1902_p4 = {{mul_ln1118_8_reg_2760[13:2]}};

assign trunc_ln708_134_fu_1944_p4 = {{mul_ln1118_9_reg_2765[13:2]}};

assign trunc_ln708_135_fu_1986_p4 = {{mul_ln1118_10_reg_2770[13:2]}};

assign trunc_ln708_136_fu_2028_p4 = {{mul_ln1118_11_reg_2775[13:2]}};

assign trunc_ln708_137_fu_2070_p4 = {{mul_ln1118_12_reg_2780[13:2]}};

assign trunc_ln708_138_fu_2112_p4 = {{mul_ln1118_13_reg_2785[13:2]}};

assign trunc_ln708_139_fu_2154_p4 = {{mul_ln1118_14_reg_2790[13:2]}};

assign trunc_ln708_140_fu_2238_p4 = {{mul_ln1118_16_reg_2800[13:2]}};

assign trunc_ln708_141_fu_2280_p4 = {{mul_ln1118_17_reg_2805[13:2]}};

assign trunc_ln708_142_fu_2322_p4 = {{mul_ln1118_18_reg_2810[13:2]}};

assign trunc_ln708_143_fu_2364_p4 = {{mul_ln1118_19_reg_2815[12:2]}};

assign trunc_ln708_s_fu_2196_p4 = {{mul_ln1118_15_reg_2795[13:2]}};

assign w8_V_address0 = zext_ln155_fu_1214_p1;

assign w_index_fu_1242_p2 = (6'd1 + ap_phi_mux_w_index81_phi_fu_741_p6);

assign zext_ln155_fu_1214_p1 = ap_phi_mux_w_index81_phi_fu_741_p6;

endmodule //dense_resource
